export const SQL_KEYWORDS = [
  'SELECT', 'FROM', 'WHERE', 'AND', 'OR', 'NOT', 'IN', 'IS', 'NULL',
  'AS', 'ON', 'JOIN', 'LEFT', 'RIGHT', 'INNER', 'OUTER', 'FULL', 'CROSS',
  'ORDER', 'BY', 'GROUP', 'HAVING', 'LIMIT', 'OFFSET', 'UNION', 'ALL',
  'INSERT', 'INTO', 'VALUES', 'UPDATE', 'SET', 'DELETE', 'CREATE', 'DROP',
  'ALTER', 'TABLE', 'VIEW', 'INDEX', 'DISTINCT', 'COUNT', 'SUM', 'AVG',
  'MIN', 'MAX', 'CASE', 'WHEN', 'THEN', 'ELSE', 'END', 'BETWEEN', 'LIKE',
  'ILIKE', 'EXISTS', 'TRUE', 'FALSE', 'ASC', 'DESC', 'NULLS', 'FIRST',
  'LAST', 'COALESCE', 'CAST', 'WITH', 'RECURSIVE', 'OVER', 'PARTITION',
  'ROW_NUMBER', 'RANK', 'DENSE_RANK', 'LATERAL', 'FILTER', 'ARRAY_AGG',
  'STRING_AGG', 'JSON_AGG', 'JSONB_AGG', 'NOW', 'CURRENT_TIMESTAMP',
  'EXTRACT', 'INTERVAL', 'DATE', 'TIMESTAMP', 'TIMESTAMPTZ',
  'INTEGER', 'TEXT', 'BOOLEAN', 'DOUBLE', 'PRECISION', 'VARCHAR', 'JSONB',
]
